Creating shadow database...
Initialising schema...
Seeding globals from roles.sql...
Applying migration 20251209120104_init_auth_schema.sql...
Applying migration 20251209123645_strict_rls.sql...
Applying migration 20251209133753_create_grievances.sql...
Applying migration 20251209142940_create_inventory.sql...
Applying migration 20251209144641_create_properties.sql...
Applying migration 20251209145111_add_verification.sql...
Applying migration 20251209153629_update_rooms.sql...
Applying migration 20251209154129_create_tenant_assignments.sql...
ERROR: relation "public.users" does not exist (SQLSTATE 42P01)                                            
At statement: 0                                                                                           
-- Create table for linking tenants to rooms                                                              
CREATE TABLE public.tenant_room_assignments (                                                             
    id UUID NOT NULL DEFAULT gen_random_uuid(),                                                           
    tenant_id UUID NOT NULL,                                                                              
    room_id UUID NOT NULL,                                                                                
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,                                                        
    end_date DATE,                                                                                        
    is_active BOOLEAN NOT NULL DEFAULT TRUE,                                                              
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),                                           
                                                                                                          
    CONSTRAINT tenant_room_assignments_pkey PRIMARY KEY (id),                                             
    CONSTRAINT tenant_room_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.users(id),
    CONSTRAINT tenant_room_assignments_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id)     
)                                                                                                         
Try rerunning the command with --debug to troubleshoot the error.
