Creating shadow database...
Initialising schema...
Seeding globals from roles.sql...
Applying migration 20251209120104_init_auth_schema.sql...
Applying migration 20251209123645_strict_rls.sql...
Applying migration 20251209133753_create_grievances.sql...
Applying migration 20251209142940_create_inventory.sql...
Applying migration 20251209144641_create_properties.sql...
Applying migration 20251209145111_add_verification.sql...
Applying migration 20251209153629_update_rooms.sql...
Applying migration 20251209154129_create_tenant_assignments.sql...
Applying migration 20251209154758_create_invoices.sql...
ERROR: relation "public.users" does not exist (SQLSTATE 42P01)                            
At statement: 1                                                                           
CREATE TABLE public.invoices (                                                            
    id UUID NOT NULL DEFAULT gen_random_uuid(),                                           
    tenant_id UUID NOT NULL,                                                              
    amount NUMERIC(10, 2) NOT NULL,                                                       
    due_date DATE NOT NULL,                                                               
    status public.invoice_status NOT NULL DEFAULT 'unpaid',                               
    description TEXT NOT NULL DEFAULT 'Rent', -- Simple description for MVP               
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),                           
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),                           
                                                                                          
    CONSTRAINT invoices_pkey PRIMARY KEY (id),                                            
    CONSTRAINT invoices_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.users(id)
)                                                                                         
Try rerunning the command with --debug to troubleshoot the error.
