Creating shadow database...
Initialising schema...
Seeding globals from roles.sql...
Applying migration 20251209120104_init_auth_schema.sql...
Applying migration 20251209123645_strict_rls.sql...
Applying migration 20251209133753_create_grievances.sql...
Applying migration 20251209142940_create_inventory.sql...
Applying migration 20251209144641_create_properties.sql...
ERROR: insert or update on table "properties" violates foreign key constraint "properties_owner_id_fkey" (SQLSTATE 23503)                                                                                                                                                                      
Key (owner_id)=(00000000-0000-0000-0000-000000000000) is not present in table "users".                                                                                                                                                                                                         
At statement: 5                                                                                                                                                                                                                                                                                
-- Seed Data (Create a property and link existing rooms)                                                                                                                                                                                                                                       
-- We need to find an owner ID. Since this is SQL migration, we can't easily grab a specific user ID unless we know it.                                                                                                                                                                        
-- Strategy: We will create a property and assign it to the *first* owner we find in the auth system, OR                                                                                                                                                                                       
-- for development predictability, we just insert one and rely on the Dashboard to assign it later or let it be 'orphaned' but viewable by ID.                                                                                                                                                 
-- Better yet: If we are just viewing by ID in the public page, the owner_id doesn't strictly matter for the *view* unless we filter.                                                                                                                                                          
-- Let's just create one.                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                               
INSERT INTO public.properties (id, owner_id, name, address, description, amenities)                                                                                                                                                                                                            
VALUES                                                                                                                                                                                                                                                                                         
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '00000000-0000-0000-0000-000000000000', 'Sunset Hive Boarding House', '123 Mango Avenue, Cebu City', 'A cozy and secure home for students and professionals. Walking distance to IT Park.', ARRAY['Fast Wifi', 'CCTV', 'Weekly Cleaning', 'Aircon'])
ON CONFLICT DO NOTHING                                                                                                                                                                                                                                                                         
Try rerunning the command with --debug to troubleshoot the error.
